language: android

jdk: oraclejdk8
sudo: false
os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/3.1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
    - $HOME/.m2

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: false

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
